package com.benner.regulacao;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class controle implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("SLA de cada sub-processo")
	private java.lang.String sla;

	@org.kie.api.definition.type.Label("Exceção")
	private Boolean excecao;

	@org.kie.api.definition.type.Description("Urgência emergência confirmada")
	@org.kie.api.definition.type.Label("Urgência / emergência confirmada?")
	private java.lang.Boolean urg_emerg_confirmada;

	@org.kie.api.definition.type.Label("Prestador fora do domicílio?")
	private java.lang.Boolean prestador_fora_domicilio;

	@org.kie.api.definition.type.Label("Operadora reverteu as negativas?")
	private java.lang.Boolean operadora_negativas_revertidas;

	@org.kie.api.definition.type.Label("Exige documentação")
	private java.lang.Boolean exigedocumentacao;

	@org.kie.api.definition.type.Label("Documentação")
	private java.lang.Boolean documentacaook;

	@org.kie.api.definition.type.Label("É OPME?")
	private java.lang.Boolean eh_opme;

	@org.kie.api.definition.type.Label("É uma solicitação oncológica?")
	private Boolean eh_oncologica;

	@org.kie.api.definition.type.Label("Tipo de SP/SADT")
	private java.lang.String tipo_sadt;

	@org.kie.api.definition.type.Label("SLA para uma terefa humada")
	private java.lang.String sla_human_task;

	@org.kie.api.definition.type.Label("Negativa cadastral?")
	private java.lang.Boolean negativa_cadastral;

	@org.kie.api.definition.type.Label("O prestador atualizou os documentos?")
	private java.lang.Boolean documentacaofornecida;

	@org.kie.api.definition.type.Label("É DUT ou alta complexidade?")
	private java.lang.Boolean eh_dut_alta_complexidade_cirurgico;

	@org.kie.api.definition.type.Label("Papel administrativo")
	private java.lang.String pp_adm;

	@org.kie.api.definition.type.Label("Papel cliente")
	private java.lang.String pp_cli;

	@org.kie.api.definition.type.Label("Papel odontológico")
	private java.lang.String pp_odo;

	@org.kie.api.definition.type.Label("Papel prestador")
	private java.lang.String pp_pre;

	@org.kie.api.definition.type.Label("Papel enfermagem")
	private java.lang.String pp_enf;

	@org.kie.api.definition.type.Label("A regulação será realizada pelo cliente")
	private java.lang.Boolean regulacao_efetuada_pelo_cliente;

	@org.kie.api.definition.type.Label("SLA geral do processo de regulacao")
	private java.lang.String sla_geral;

	@javax.persistence.Id
	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO)
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Papel médico")
	private java.lang.String pp_med;

	@org.kie.api.definition.type.Label("O parecer final é dado pelo cliente?")
	private java.lang.Boolean parecer_final_do_cliente;

	@org.kie.api.definition.type.Label("Reiniciar o processo de regulação (rever documentação).")
	private java.lang.Boolean reprocessar;

	@org.kie.api.definition.type.Label("Tipo da guia")
	private java.lang.String tipo_guia;

	@org.kie.api.definition.type.Label("Caráter atendimento")
	private Integer carater_atendimento;

	@org.kie.api.definition.type.Label("Registro ANS")
	private long registro_ans;

	@org.kie.api.definition.type.Label("Situação da guia originalmente")
	private java.lang.String situacao_original;

	@org.kie.api.definition.type.Label("Situação para a regulação")
	private java.lang.String situacao_regulacao;

	@org.kie.api.definition.type.Label("Parecer final - anotações")
	private java.lang.String parecer_final;

	@org.kie.api.definition.type.Label("Parecer sobre DUT / alta complexidade")
	private java.lang.String parecer_dut_alta_complexidade;

	@org.kie.api.definition.type.Label("Id do processo")
	private java.lang.Long process_id;

	@org.kie.api.definition.type.Label("Guia")
	private java.lang.Long guia_id;

	@org.kie.api.definition.type.Label("Tipo da solicitacao")
	private String tipo_solicitacao;

	@org.kie.api.definition.type.Label("Radioterapia")
	private java.lang.Boolean eh_radioterapia;

	@org.kie.api.definition.type.Label("Quimioterapia?")
	private java.lang.Boolean eh_quimioterapia;

	@org.kie.api.definition.type.Label("Usuário da tafera")
	private java.lang.String usuario_tarefa;

	@org.kie.api.definition.type.Label("Beneficiário é VIP?")
	private java.lang.Boolean beneficiario_vip;

	@org.kie.api.definition.type.Label("NIP ou liminar?")
	private java.lang.Boolean nip_ou_liminar;

	@org.kie.api.definition.type.Label(value = "Regime de Internação")
	private java.lang.Integer regime_internacao;

	public controle() {
	}

	public java.lang.String getSla() {
		return this.sla;
	}

	public void setSla(java.lang.String sla) {
		this.sla = sla;
	}

	public java.lang.Boolean getUrg_emerg_confirmada() {
		return this.urg_emerg_confirmada;
	}

	public void setUrg_emerg_confirmada(java.lang.Boolean urg_emerg_confirmada) {
		this.urg_emerg_confirmada = urg_emerg_confirmada;
	}

	public java.lang.Boolean getPrestador_fora_domicilio() {
		return this.prestador_fora_domicilio;
	}

	public void setPrestador_fora_domicilio(
			java.lang.Boolean prestador_fora_domicilio) {
		this.prestador_fora_domicilio = prestador_fora_domicilio;
	}

	public java.lang.Boolean getOperadora_negativas_revertidas() {
		return this.operadora_negativas_revertidas;
	}

	public void setOperadora_negativas_revertidas(
			java.lang.Boolean operadora_negativas_revertidas) {
		this.operadora_negativas_revertidas = operadora_negativas_revertidas;
	}

	public java.lang.Boolean getExcecao() {
		return this.excecao;
	}

	public void setExcecao(java.lang.Boolean excecao) {
		this.excecao = excecao;
	}

	public java.lang.Boolean getExigedocumentacao() {
		return this.exigedocumentacao;
	}

	public void setExigedocumentacao(java.lang.Boolean exigedocumentacao) {
		this.exigedocumentacao = exigedocumentacao;
	}

	public java.lang.Boolean getDocumentacaook() {
		return this.documentacaook;
	}

	public void setDocumentacaook(java.lang.Boolean documentacaook) {
		this.documentacaook = documentacaook;
	}

	public java.lang.Boolean getEh_opme() {
		return this.eh_opme;
	}

	public void setEh_opme(java.lang.Boolean eh_opme) {
		this.eh_opme = eh_opme;
	}

	public java.lang.String getTipo_sadt() {
		return this.tipo_sadt;
	}

	public void setTipo_sadt(java.lang.String tipo_sadt) {
		this.tipo_sadt = tipo_sadt;
	}

	public java.lang.Boolean getEh_oncologica() {
		return this.eh_oncologica;
	}

	public void setEh_oncologica(java.lang.Boolean eh_oncologica) {
		this.eh_oncologica = eh_oncologica;
	}

	public java.lang.String getSla_human_task() {
		return this.sla_human_task;
	}

	public void setSla_human_task(java.lang.String sla_human_task) {
		this.sla_human_task = sla_human_task;
	}

	public java.lang.Boolean getNegativa_cadastral() {
		return this.negativa_cadastral;
	}

	public void setNegativa_cadastral(java.lang.Boolean negativa_cadastral) {
		this.negativa_cadastral = negativa_cadastral;
	}

	public java.lang.Boolean getDocumentacaofornecida() {
		return this.documentacaofornecida;
	}

	public void setDocumentacaofornecida(java.lang.Boolean documentacaofornecida) {
		this.documentacaofornecida = documentacaofornecida;
	}

	public java.lang.Boolean getEh_dut_alta_complexidade_cirurgico() {
		return this.eh_dut_alta_complexidade_cirurgico;
	}

	public void setEh_dut_alta_complexidade_cirurgico(
			java.lang.Boolean eh_dut_alta_complexidade_cirurgico) {
		this.eh_dut_alta_complexidade_cirurgico = eh_dut_alta_complexidade_cirurgico;
	}

	public java.lang.String getPp_adm() {
		return this.pp_adm;
	}

	public void setPp_adm(java.lang.String pp_adm) {
		this.pp_adm = pp_adm;
	}

	public java.lang.String getPp_cli() {
		return this.pp_cli;
	}

	public void setPp_cli(java.lang.String pp_cli) {
		this.pp_cli = pp_cli;
	}

	public java.lang.String getPp_odo() {
		return this.pp_odo;
	}

	public void setPp_odo(java.lang.String pp_odo) {
		this.pp_odo = pp_odo;
	}

	public java.lang.String getPp_pre() {
		return this.pp_pre;
	}

	public void setPp_pre(java.lang.String pp_pre) {
		this.pp_pre = pp_pre;
	}

	public java.lang.String getPp_enf() {
		return this.pp_enf;
	}

	public void setPp_enf(java.lang.String pp_enf) {
		this.pp_enf = pp_enf;
	}

	public java.lang.Boolean getRegulacao_efetuada_pelo_cliente() {
		return this.regulacao_efetuada_pelo_cliente;
	}

	public void setRegulacao_efetuada_pelo_cliente(
			java.lang.Boolean regulacao_efetuada_pelo_cliente) {
		this.regulacao_efetuada_pelo_cliente = regulacao_efetuada_pelo_cliente;
	}

	public java.lang.String getSla_geral() {
		return this.sla_geral;
	}

	public void setSla_geral(java.lang.String sla_geral) {
		this.sla_geral = sla_geral;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getPp_med() {
		return this.pp_med;
	}

	public void setPp_med(java.lang.String pp_med) {
		this.pp_med = pp_med;
	}

	public java.lang.Boolean getParecer_final_do_cliente() {
		return this.parecer_final_do_cliente;
	}

	public void setParecer_final_do_cliente(
			java.lang.Boolean parecer_final_do_cliente) {
		this.parecer_final_do_cliente = parecer_final_do_cliente;
	}

	public java.lang.Boolean getReprocessar() {
		return this.reprocessar;
	}

	public void setReprocessar(java.lang.Boolean reprocessar) {
		this.reprocessar = reprocessar;
	}

	public java.lang.String getTipo_guia() {
		return this.tipo_guia;
	}

	public void setTipo_guia(java.lang.String tipo_guia) {
		this.tipo_guia = tipo_guia;
	}

	public long getRegistro_ans() {
		return this.registro_ans;
	}

	public void setRegistro_ans(long registro_ans) {
		this.registro_ans = registro_ans;
	}

	public java.lang.String getSituacao_original() {
		return this.situacao_original;
	}

	public void setSituacao_original(java.lang.String situacao_original) {
		this.situacao_original = situacao_original;
	}

	public java.lang.String getSituacao_regulacao() {
		return this.situacao_regulacao;
	}

	public void setSituacao_regulacao(java.lang.String situacao_regulacao) {
		this.situacao_regulacao = situacao_regulacao;
	}

	public java.lang.String getParecer_final() {
		return this.parecer_final;
	}

	public void setParecer_final(java.lang.String parecer_final) {
		this.parecer_final = parecer_final;
	}

	public java.lang.String getParecer_dut_alta_complexidade() {
		return this.parecer_dut_alta_complexidade;
	}

	public void setParecer_dut_alta_complexidade(
			java.lang.String parecer_dut_alta_complexidade) {
		this.parecer_dut_alta_complexidade = parecer_dut_alta_complexidade;
	}

	public java.lang.Long getProcess_id() {
		return this.process_id;
	}

	public void setProcess_id(java.lang.Long process_id) {
		this.process_id = process_id;
	}

	public java.lang.Long getGuia_id() {
		return this.guia_id;
	}

	public void setGuia_id(java.lang.Long guia_id) {
		this.guia_id = guia_id;
	}

	public java.lang.String getTipo_solicitacao() {
		return this.tipo_solicitacao;
	}

	public void setTipo_solicitacao(java.lang.String tipo_solicitacao) {
		this.tipo_solicitacao = tipo_solicitacao;
	}

	public java.lang.Integer getCarater_atendimento() {
		return this.carater_atendimento;
	}

	public void setCarater_atendimento(java.lang.Integer carater_atendimento) {
		this.carater_atendimento = carater_atendimento;
	}

	public java.lang.Boolean getEh_radioterapia() {
		return this.eh_radioterapia;
	}

	public void setEh_radioterapia(java.lang.Boolean eh_radioterapia) {
		this.eh_radioterapia = eh_radioterapia;
	}

	public java.lang.Boolean getEh_quimioterapia() {
		return this.eh_quimioterapia;
	}

	public void setEh_quimioterapia(java.lang.Boolean eh_quimioterapia) {
		this.eh_quimioterapia = eh_quimioterapia;
	}

	public java.lang.String getUsuario_tarefa() {
		return this.usuario_tarefa;
	}

	public void setUsuario_tarefa(java.lang.String usuario_tarefa) {
		this.usuario_tarefa = usuario_tarefa;
	}

	public java.lang.Boolean getBeneficiario_vip() {
		return this.beneficiario_vip;
	}

	public void setBeneficiario_vip(java.lang.Boolean beneficiario_vip) {
		this.beneficiario_vip = beneficiario_vip;
	}

	public java.lang.Boolean getNip_ou_liminar() {
		return this.nip_ou_liminar;
	}

	public void setNip_ou_liminar(java.lang.Boolean nip_ou_liminar) {
		this.nip_ou_liminar = nip_ou_liminar;
	}

	public java.lang.Integer getRegime_internacao() {
		return this.regime_internacao;
	}

	public void setRegime_internacao(java.lang.Integer regime_internacao) {
		this.regime_internacao = regime_internacao;
	}

	public controle(java.lang.String sla, java.lang.Boolean excecao,
			java.lang.Boolean urg_emerg_confirmada,
			java.lang.Boolean prestador_fora_domicilio,
			java.lang.Boolean operadora_negativas_revertidas,
			java.lang.Boolean exigedocumentacao,
			java.lang.Boolean documentacaook, java.lang.Boolean eh_opme,
			java.lang.Boolean eh_oncologica, java.lang.String tipo_sadt,
			java.lang.String sla_human_task,
			java.lang.Boolean negativa_cadastral,
			java.lang.Boolean documentacaofornecida,
			java.lang.Boolean eh_dut_alta_complexidade_cirurgico,
			java.lang.String pp_adm, java.lang.String pp_cli,
			java.lang.String pp_odo, java.lang.String pp_pre,
			java.lang.String pp_enf,
			java.lang.Boolean regulacao_efetuada_pelo_cliente,
			java.lang.String sla_geral, java.lang.Long id,
			java.lang.String pp_med,
			java.lang.Boolean parecer_final_do_cliente,
			java.lang.Boolean reprocessar, java.lang.String tipo_guia,
			java.lang.Integer carater_atendimento, long registro_ans,
			java.lang.String situacao_original,
			java.lang.String situacao_regulacao,
			java.lang.String parecer_final,
			java.lang.String parecer_dut_alta_complexidade,
			java.lang.Long process_id, java.lang.Long guia_id,
			java.lang.String tipo_solicitacao,
			java.lang.Boolean eh_radioterapia,
			java.lang.Boolean eh_quimioterapia,
			java.lang.String usuario_tarefa,
			java.lang.Boolean beneficiario_vip,
			java.lang.Boolean nip_ou_liminar,
			java.lang.Integer regime_internacao) {
		this.sla = sla;
		this.excecao = excecao;
		this.urg_emerg_confirmada = urg_emerg_confirmada;
		this.prestador_fora_domicilio = prestador_fora_domicilio;
		this.operadora_negativas_revertidas = operadora_negativas_revertidas;
		this.exigedocumentacao = exigedocumentacao;
		this.documentacaook = documentacaook;
		this.eh_opme = eh_opme;
		this.eh_oncologica = eh_oncologica;
		this.tipo_sadt = tipo_sadt;
		this.sla_human_task = sla_human_task;
		this.negativa_cadastral = negativa_cadastral;
		this.documentacaofornecida = documentacaofornecida;
		this.eh_dut_alta_complexidade_cirurgico = eh_dut_alta_complexidade_cirurgico;
		this.pp_adm = pp_adm;
		this.pp_cli = pp_cli;
		this.pp_odo = pp_odo;
		this.pp_pre = pp_pre;
		this.pp_enf = pp_enf;
		this.regulacao_efetuada_pelo_cliente = regulacao_efetuada_pelo_cliente;
		this.sla_geral = sla_geral;
		this.id = id;
		this.pp_med = pp_med;
		this.parecer_final_do_cliente = parecer_final_do_cliente;
		this.reprocessar = reprocessar;
		this.tipo_guia = tipo_guia;
		this.carater_atendimento = carater_atendimento;
		this.registro_ans = registro_ans;
		this.situacao_original = situacao_original;
		this.situacao_regulacao = situacao_regulacao;
		this.parecer_final = parecer_final;
		this.parecer_dut_alta_complexidade = parecer_dut_alta_complexidade;
		this.process_id = process_id;
		this.guia_id = guia_id;
		this.tipo_solicitacao = tipo_solicitacao;
		this.eh_radioterapia = eh_radioterapia;
		this.eh_quimioterapia = eh_quimioterapia;
		this.usuario_tarefa = usuario_tarefa;
		this.beneficiario_vip = beneficiario_vip;
		this.nip_ou_liminar = nip_ou_liminar;
		this.regime_internacao = regime_internacao;
	}

}