package com.benner.regulacao;
/**
 * This class was automatically generated by the data modeler tool.
 */
@javax.persistence.Entity
@org.kie.api.definition.type.Label("Guia")
public class guia implements java.io.Serializable {
	static final long serialVersionUID = 1L;
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "GUIA_ID_SEQ", name = "GUIA_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Possui anexo clinico")
	private java.lang.Boolean anexoclinico;
	@org.kie.api.definition.type.Label("Atendimento RN")
	private Boolean atendimentorn;
	@org.kie.api.definition.type.Label("Sem codigo de validacao")
	private java.lang.String ausenciacodvalidacao;
	@org.kie.api.definition.type.Label("Carater de atendimento")
	private java.lang.String carateratendimento;
	@org.kie.api.definition.type.Label("CBOS")
	private java.lang.String cbos;
	@org.kie.api.definition.type.Label("CNPJ do contratado")
	private java.lang.String cnpjcontratado;
	@org.kie.api.definition.type.Label("Codigo do indicado na operadora")
	private java.lang.String codigoindicadonaoperadora;
	@org.kie.api.definition.type.Label("Codigo do prestador na operadora")
	private java.lang.String codigoprestadornaoperadora;
	@org.kie.api.definition.type.Label("Código de validação")
	private java.lang.String codvalidacao;
	@org.kie.api.definition.type.Label("Conselho profissional")
	private java.lang.String conselhoprofissional;
	@org.kie.api.definition.type.Label("CPF do contratado")
	private java.lang.String cpfcontratado;
	@org.kie.api.definition.type.Label("Data da solicitacao")
	private java.time.LocalDateTime datasolicitacao;
	@org.kie.api.definition.type.Label("Data sugerida de internacao")
	private java.time.LocalDateTime datasugeridainternacao;
	@org.kie.api.definition.type.Label("CID do dignostico")
	private java.lang.String diagnosticocid;
	@org.kie.api.definition.type.Label("Identificador do beneficiario")
	private java.lang.String identificadorbeneficiario;
	@org.kie.api.definition.type.Label("Indicação clinica")
	private java.lang.String indicacaoclinica;
	@org.kie.api.definition.type.Label("Indicador acidente")
	private java.lang.String indicadoracidente;
	@org.kie.api.definition.type.Label("Indicador OPME")
	private java.lang.Boolean indicadoropme;
	@org.kie.api.definition.type.Label("Indicador quimio")
	private java.lang.Boolean indicadorquimio;
	@org.kie.api.definition.type.Label("Nome do beneficiario")
	private java.lang.String nomebeneficiario;
	@org.kie.api.definition.type.Label("Nome do contratado indicado")
	private java.lang.String nomecontratadoindicado;
	@org.kie.api.definition.type.Label("Nome do profissional")
	private java.lang.String nomeprofissional;
	@org.kie.api.definition.type.Label("Número da carteira")
	private java.lang.String numerocarteira;
	@org.kie.api.definition.type.Label("C.N.S. (Cart nacional de saúde)")
	private java.lang.String numerocns;
	@org.kie.api.definition.type.Label("Conselho profissional")
	private java.lang.String numeroconselhoprofissional;
	@org.kie.api.definition.type.Label("Núm da guia no prestador")
	private java.lang.String numeroguiaprestador;
	@org.kie.api.definition.type.Label("Guia principal")
	private java.lang.String numeroguiaprincipal;
	@org.kie.api.definition.type.Label("Observacoes")
	private java.lang.String observacao;
	@org.kie.api.definition.type.Label("Quantidade solicitada")
	private int qtdiariassolicitadas;
	@org.kie.api.definition.type.Label("Regime da internacao")
	private java.lang.String regimeinternacao;
	@org.kie.api.definition.type.Label("Observações da regulacao")
	private java.lang.String regulobservacao;
	@org.kie.api.definition.type.Label("Quantidade de diarias liberada")
	private int regulqtdiariasliberadas;
	@org.kie.api.definition.type.Label("Situacao")
	private java.lang.String regulsituacao;
	@org.kie.api.definition.type.Label("Situacao apos analise")
	private java.lang.String regulsituacaoaposanalise;
	@org.kie.api.definition.type.Label("Tipo da guia")
	private java.lang.String regultipoguia;
	@org.kie.api.definition.type.Label("Solicitacao de OPME?")
	private java.lang.Boolean solicitacaoopme;
	@org.kie.api.definition.type.Label("Solicitacao de quimio?")
	private java.lang.Boolean solicitacaoquimioterapia;
	@org.kie.api.definition.type.Label("Solicitacao de radio?")
	private java.lang.Boolean solicitacaoradioterapia;
	@org.kie.api.definition.type.Label("Biometria")
	private java.lang.String templatebiometrico;
	@org.kie.api.definition.type.Label("Tipo da etapa")
	private java.lang.String tipoetapaautorizacao;
	@org.kie.api.definition.type.Label("Tipo da identificacao")
	private java.lang.String tipoident;
	@org.kie.api.definition.type.Label("Tipo internacao")
	private java.lang.String tipointernacao;
	@org.kie.api.definition.type.Label("UF")
	private java.lang.String uf;

	@javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL}, mappedBy = "idguia", targetEntity = guiaeventos.class)
	@org.kie.api.definition.type.Label("Eventos")
	private java.util.List<com.benner.regulacao.guiaeventos> eventos;

	@org.kie.api.definition.type.Label("Registro ANS")
	private Long registroans;

	public guia() {
	}
	public java.lang.Boolean getAnexoclinico() {
		return this.anexoclinico;
	}
	public void setAnexoclinico(java.lang.Boolean anexoclinico) {
		this.anexoclinico = anexoclinico;
	}
	public java.lang.String getAusenciacodvalidacao() {
		return this.ausenciacodvalidacao;
	}
	public void setAusenciacodvalidacao(java.lang.String ausenciacodvalidacao) {
		this.ausenciacodvalidacao = ausenciacodvalidacao;
	}
	public java.lang.String getCarateratendimento() {
		return this.carateratendimento;
	}
	public void setCarateratendimento(java.lang.String carateratendimento) {
		this.carateratendimento = carateratendimento;
	}
	public java.lang.String getCbos() {
		return this.cbos;
	}
	public void setCbos(java.lang.String cbos) {
		this.cbos = cbos;
	}
	public java.lang.String getCnpjcontratado() {
		return this.cnpjcontratado;
	}
	public void setCnpjcontratado(java.lang.String cnpjcontratado) {
		this.cnpjcontratado = cnpjcontratado;
	}
	public java.lang.String getCodigoindicadonaoperadora() {
		return this.codigoindicadonaoperadora;
	}
	public void setCodigoindicadonaoperadora(
			java.lang.String codigoindicadonaoperadora) {
		this.codigoindicadonaoperadora = codigoindicadonaoperadora;
	}
	public java.lang.String getCodigoprestadornaoperadora() {
		return this.codigoprestadornaoperadora;
	}
	public void setCodigoprestadornaoperadora(
			java.lang.String codigoprestadornaoperadora) {
		this.codigoprestadornaoperadora = codigoprestadornaoperadora;
	}
	public java.lang.String getCodvalidacao() {
		return this.codvalidacao;
	}
	public void setCodvalidacao(java.lang.String codvalidacao) {
		this.codvalidacao = codvalidacao;
	}
	public java.lang.String getConselhoprofissional() {
		return this.conselhoprofissional;
	}
	public void setConselhoprofissional(java.lang.String conselhoprofissional) {
		this.conselhoprofissional = conselhoprofissional;
	}
	public java.lang.String getCpfcontratado() {
		return this.cpfcontratado;
	}
	public void setCpfcontratado(java.lang.String cpfcontratado) {
		this.cpfcontratado = cpfcontratado;
	}
	public java.time.LocalDateTime getDatasolicitacao() {
		return this.datasolicitacao;
	}
	public void setDatasolicitacao(java.time.LocalDateTime datasolicitacao) {
		this.datasolicitacao = datasolicitacao;
	}
	public java.time.LocalDateTime getDatasugeridainternacao() {
		return this.datasugeridainternacao;
	}
	public void setDatasugeridainternacao(
			java.time.LocalDateTime datasugeridainternacao) {
		this.datasugeridainternacao = datasugeridainternacao;
	}
	public java.lang.String getDiagnosticocid() {
		return this.diagnosticocid;
	}
	public void setDiagnosticocid(java.lang.String diagnosticocid) {
		this.diagnosticocid = diagnosticocid;
	}
	public java.lang.Long getId() {
		return this.id;
	}
	public void setId(java.lang.Long id) {
		this.id = id;
	}
	public java.lang.String getIdentificadorbeneficiario() {
		return this.identificadorbeneficiario;
	}
	public void setIdentificadorbeneficiario(
			java.lang.String identificadorbeneficiario) {
		this.identificadorbeneficiario = identificadorbeneficiario;
	}
	public java.lang.String getIndicacaoclinica() {
		return this.indicacaoclinica;
	}
	public void setIndicacaoclinica(java.lang.String indicacaoclinica) {
		this.indicacaoclinica = indicacaoclinica;
	}
	public java.lang.String getIndicadoracidente() {
		return this.indicadoracidente;
	}
	public void setIndicadoracidente(java.lang.String indicadoracidente) {
		this.indicadoracidente = indicadoracidente;
	}
	public java.lang.Boolean getIndicadoropme() {
		return this.indicadoropme;
	}
	public void setIndicadoropme(java.lang.Boolean indicadoropme) {
		this.indicadoropme = indicadoropme;
	}
	public java.lang.Boolean getIndicadorquimio() {
		return this.indicadorquimio;
	}
	public void setIndicadorquimio(java.lang.Boolean indicadorquimio) {
		this.indicadorquimio = indicadorquimio;
	}
	public java.lang.String getNomebeneficiario() {
		return this.nomebeneficiario;
	}
	public void setNomebeneficiario(java.lang.String nomebeneficiario) {
		this.nomebeneficiario = nomebeneficiario;
	}
	public java.lang.String getNomecontratadoindicado() {
		return this.nomecontratadoindicado;
	}
	public void setNomecontratadoindicado(
			java.lang.String nomecontratadoindicado) {
		this.nomecontratadoindicado = nomecontratadoindicado;
	}
	public java.lang.String getNomeprofissional() {
		return this.nomeprofissional;
	}
	public void setNomeprofissional(java.lang.String nomeprofissional) {
		this.nomeprofissional = nomeprofissional;
	}
	public java.lang.String getNumerocarteira() {
		return this.numerocarteira;
	}
	public void setNumerocarteira(java.lang.String numerocarteira) {
		this.numerocarteira = numerocarteira;
	}
	public java.lang.String getNumerocns() {
		return this.numerocns;
	}
	public void setNumerocns(java.lang.String numerocns) {
		this.numerocns = numerocns;
	}
	public java.lang.String getNumeroconselhoprofissional() {
		return this.numeroconselhoprofissional;
	}
	public void setNumeroconselhoprofissional(
			java.lang.String numeroconselhoprofissional) {
		this.numeroconselhoprofissional = numeroconselhoprofissional;
	}
	public java.lang.String getNumeroguiaprestador() {
		return this.numeroguiaprestador;
	}
	public void setNumeroguiaprestador(java.lang.String numeroguiaprestador) {
		this.numeroguiaprestador = numeroguiaprestador;
	}
	public java.lang.String getNumeroguiaprincipal() {
		return this.numeroguiaprincipal;
	}
	public void setNumeroguiaprincipal(java.lang.String numeroguiaprincipal) {
		this.numeroguiaprincipal = numeroguiaprincipal;
	}
	public java.lang.String getObservacao() {
		return this.observacao;
	}
	public void setObservacao(java.lang.String observacao) {
		this.observacao = observacao;
	}
	public int getQtdiariassolicitadas() {
		return this.qtdiariassolicitadas;
	}
	public void setQtdiariassolicitadas(int qtdiariassolicitadas) {
		this.qtdiariassolicitadas = qtdiariassolicitadas;
	}
	public java.lang.String getRegimeinternacao() {
		return this.regimeinternacao;
	}
	public void setRegimeinternacao(java.lang.String regimeinternacao) {
		this.regimeinternacao = regimeinternacao;
	}
	public java.lang.String getRegulobservacao() {
		return this.regulobservacao;
	}
	public void setRegulobservacao(java.lang.String regulobservacao) {
		this.regulobservacao = regulobservacao;
	}
	public int getRegulqtdiariasliberadas() {
		return this.regulqtdiariasliberadas;
	}
	public void setRegulqtdiariasliberadas(int regulqtdiariasliberadas) {
		this.regulqtdiariasliberadas = regulqtdiariasliberadas;
	}
	public java.lang.String getRegulsituacao() {
		return this.regulsituacao;
	}
	public void setRegulsituacao(java.lang.String regulsituacao) {
		this.regulsituacao = regulsituacao;
	}
	public java.lang.String getRegulsituacaoaposanalise() {
		return this.regulsituacaoaposanalise;
	}
	public void setRegulsituacaoaposanalise(
			java.lang.String regulsituacaoaposanalise) {
		this.regulsituacaoaposanalise = regulsituacaoaposanalise;
	}
	public java.lang.String getRegultipoguia() {
		return this.regultipoguia;
	}
	public void setRegultipoguia(java.lang.String regultipoguia) {
		this.regultipoguia = regultipoguia;
	}
	public java.lang.Boolean getSolicitacaoopme() {
		return this.solicitacaoopme;
	}
	public void setSolicitacaoopme(java.lang.Boolean solicitacaoopme) {
		this.solicitacaoopme = solicitacaoopme;
	}
	public java.lang.Boolean getSolicitacaoquimioterapia() {
		return this.solicitacaoquimioterapia;
	}
	public void setSolicitacaoquimioterapia(
			java.lang.Boolean solicitacaoquimioterapia) {
		this.solicitacaoquimioterapia = solicitacaoquimioterapia;
	}
	public java.lang.Boolean getSolicitacaoradioterapia() {
		return this.solicitacaoradioterapia;
	}
	public void setSolicitacaoradioterapia(
			java.lang.Boolean solicitacaoradioterapia) {
		this.solicitacaoradioterapia = solicitacaoradioterapia;
	}
	public java.lang.String getTemplatebiometrico() {
		return this.templatebiometrico;
	}
	public void setTemplatebiometrico(java.lang.String templatebiometrico) {
		this.templatebiometrico = templatebiometrico;
	}
	public java.lang.String getTipoetapaautorizacao() {
		return this.tipoetapaautorizacao;
	}
	public void setTipoetapaautorizacao(java.lang.String tipoetapaautorizacao) {
		this.tipoetapaautorizacao = tipoetapaautorizacao;
	}
	public java.lang.String getTipoident() {
		return this.tipoident;
	}
	public void setTipoident(java.lang.String tipoident) {
		this.tipoident = tipoident;
	}
	public java.lang.String getTipointernacao() {
		return this.tipointernacao;
	}
	public void setTipointernacao(java.lang.String tipointernacao) {
		this.tipointernacao = tipointernacao;
	}
	public java.lang.String getUf() {
		return this.uf;
	}
	public void setUf(java.lang.String uf) {
		this.uf = uf;
	}
	public guia(java.lang.Boolean anexoclinico,
			java.lang.Boolean atendimentorn,
			java.lang.String ausenciacodvalidacao,
			java.lang.String carateratendimento, java.lang.String cbos,
			java.lang.String cnpjcontratado,
			java.lang.String codigoindicadonaoperadora,
			java.lang.String codigoprestadornaoperadora,
			java.lang.String codvalidacao,
			java.lang.String conselhoprofissional,
			java.lang.String cpfcontratado,
			java.time.LocalDateTime datasolicitacao,
			java.time.LocalDateTime datasugeridainternacao,
			java.lang.String diagnosticocid, java.lang.Long id,
			java.lang.String identificadorbeneficiario,
			java.lang.String indicacaoclinica,
			java.lang.String indicadoracidente,
			java.lang.Boolean indicadoropme, java.lang.Boolean indicadorquimio,
			java.lang.String nomebeneficiario,
			java.lang.String nomecontratadoindicado,
			java.lang.String nomeprofissional, java.lang.String numerocarteira,
			java.lang.String numerocns,
			java.lang.String numeroconselhoprofissional,
			java.lang.String numeroguiaprestador,
			java.lang.String numeroguiaprincipal, java.lang.String observacao,
			int qtdiariassolicitadas, java.lang.String regimeinternacao,
			java.lang.String registro_ans, java.lang.String regulobservacao,
			int regulqtdiariasliberadas, java.lang.String regulsituacao,
			java.lang.String regulsituacaoaposanalise,
			java.lang.String regultipoguia, java.lang.Boolean solicitacaoopme,
			java.lang.Boolean solicitacaoquimioterapia,
			java.lang.Boolean solicitacaoradioterapia,
			java.lang.String templatebiometrico,
			java.lang.String tipoetapaautorizacao, java.lang.String tipoident,
			java.lang.String tipointernacao, java.lang.String uf) {
		this.anexoclinico = anexoclinico;
		this.atendimentorn = atendimentorn;
		this.ausenciacodvalidacao = ausenciacodvalidacao;
		this.carateratendimento = carateratendimento;
		this.cbos = cbos;
		this.cnpjcontratado = cnpjcontratado;
		this.codigoindicadonaoperadora = codigoindicadonaoperadora;
		this.codigoprestadornaoperadora = codigoprestadornaoperadora;
		this.codvalidacao = codvalidacao;
		this.conselhoprofissional = conselhoprofissional;
		this.cpfcontratado = cpfcontratado;
		this.datasolicitacao = datasolicitacao;
		this.datasugeridainternacao = datasugeridainternacao;
		this.diagnosticocid = diagnosticocid;
		this.id = id;
		this.identificadorbeneficiario = identificadorbeneficiario;
		this.indicacaoclinica = indicacaoclinica;
		this.indicadoracidente = indicadoracidente;
		this.indicadoropme = indicadoropme;
		this.indicadorquimio = indicadorquimio;
		this.nomebeneficiario = nomebeneficiario;
		this.nomecontratadoindicado = nomecontratadoindicado;
		this.nomeprofissional = nomeprofissional;
		this.numerocarteira = numerocarteira;
		this.numerocns = numerocns;
		this.numeroconselhoprofissional = numeroconselhoprofissional;
		this.numeroguiaprestador = numeroguiaprestador;
		this.numeroguiaprincipal = numeroguiaprincipal;
		this.observacao = observacao;
		this.qtdiariassolicitadas = qtdiariassolicitadas;
		this.regimeinternacao = regimeinternacao;
		this.registroans = registroans;
		this.regulobservacao = regulobservacao;
		this.regulqtdiariasliberadas = regulqtdiariasliberadas;
		this.regulsituacao = regulsituacao;
		this.regulsituacaoaposanalise = regulsituacaoaposanalise;
		this.regultipoguia = regultipoguia;
		this.solicitacaoopme = solicitacaoopme;
		this.solicitacaoquimioterapia = solicitacaoquimioterapia;
		this.solicitacaoradioterapia = solicitacaoradioterapia;
		this.templatebiometrico = templatebiometrico;
		this.tipoetapaautorizacao = tipoetapaautorizacao;
		this.tipoident = tipoident;
		this.tipointernacao = tipointernacao;
		this.uf = uf;
	}
	public java.util.List<com.benner.regulacao.guiaeventos> getEventos() {
		return this.eventos;
	}
	public void setEventos(
			java.util.List<com.benner.regulacao.guiaeventos> eventos) {
		this.eventos = eventos;
	}
	public java.lang.Boolean getAtendimentorn() {
		return this.atendimentorn;
	}
	public void setAtendimentorn(java.lang.Boolean atendimentorn) {
		this.atendimentorn = atendimentorn;
	}
	public java.lang.Long getRegistroans() {
		return this.registroans;
	}
	public void setRegistroans(java.lang.Long registroans) {
		this.registroans = registroans;
	}
	public guia(java.lang.Long id, java.lang.Boolean anexoclinico,
			java.lang.Boolean atendimentorn,
			java.lang.String ausenciacodvalidacao,
			java.lang.String carateratendimento, java.lang.String cbos,
			java.lang.String cnpjcontratado,
			java.lang.String codigoindicadonaoperadora,
			java.lang.String codigoprestadornaoperadora,
			java.lang.String codvalidacao,
			java.lang.String conselhoprofissional,
			java.lang.String cpfcontratado,
			java.time.LocalDateTime datasolicitacao,
			java.time.LocalDateTime datasugeridainternacao,
			java.lang.String diagnosticocid,
			java.lang.String identificadorbeneficiario,
			java.lang.String indicacaoclinica,
			java.lang.String indicadoracidente,
			java.lang.Boolean indicadoropme, java.lang.Boolean indicadorquimio,
			java.lang.String nomebeneficiario,
			java.lang.String nomecontratadoindicado,
			java.lang.String nomeprofissional, java.lang.String numerocarteira,
			java.lang.String numerocns,
			java.lang.String numeroconselhoprofissional,
			java.lang.String numeroguiaprestador,
			java.lang.String numeroguiaprincipal, java.lang.String observacao,
			int qtdiariassolicitadas, java.lang.String regimeinternacao,
			java.lang.String regulobservacao, int regulqtdiariasliberadas,
			java.lang.String regulsituacao,
			java.lang.String regulsituacaoaposanalise,
			java.lang.String regultipoguia, java.lang.Boolean solicitacaoopme,
			java.lang.Boolean solicitacaoquimioterapia,
			java.lang.Boolean solicitacaoradioterapia,
			java.lang.String templatebiometrico,
			java.lang.String tipoetapaautorizacao, java.lang.String tipoident,
			java.lang.String tipointernacao, java.lang.String uf,
			java.util.List<com.benner.regulacao.guiaeventos> eventos,
			java.lang.Long registroans) {
		this.id = id;
		this.anexoclinico = anexoclinico;
		this.atendimentorn = atendimentorn;
		this.ausenciacodvalidacao = ausenciacodvalidacao;
		this.carateratendimento = carateratendimento;
		this.cbos = cbos;
		this.cnpjcontratado = cnpjcontratado;
		this.codigoindicadonaoperadora = codigoindicadonaoperadora;
		this.codigoprestadornaoperadora = codigoprestadornaoperadora;
		this.codvalidacao = codvalidacao;
		this.conselhoprofissional = conselhoprofissional;
		this.cpfcontratado = cpfcontratado;
		this.datasolicitacao = datasolicitacao;
		this.datasugeridainternacao = datasugeridainternacao;
		this.diagnosticocid = diagnosticocid;
		this.identificadorbeneficiario = identificadorbeneficiario;
		this.indicacaoclinica = indicacaoclinica;
		this.indicadoracidente = indicadoracidente;
		this.indicadoropme = indicadoropme;
		this.indicadorquimio = indicadorquimio;
		this.nomebeneficiario = nomebeneficiario;
		this.nomecontratadoindicado = nomecontratadoindicado;
		this.nomeprofissional = nomeprofissional;
		this.numerocarteira = numerocarteira;
		this.numerocns = numerocns;
		this.numeroconselhoprofissional = numeroconselhoprofissional;
		this.numeroguiaprestador = numeroguiaprestador;
		this.numeroguiaprincipal = numeroguiaprincipal;
		this.observacao = observacao;
		this.qtdiariassolicitadas = qtdiariassolicitadas;
		this.regimeinternacao = regimeinternacao;
		this.regulobservacao = regulobservacao;
		this.regulqtdiariasliberadas = regulqtdiariasliberadas;
		this.regulsituacao = regulsituacao;
		this.regulsituacaoaposanalise = regulsituacaoaposanalise;
		this.regultipoguia = regultipoguia;
		this.solicitacaoopme = solicitacaoopme;
		this.solicitacaoquimioterapia = solicitacaoquimioterapia;
		this.solicitacaoradioterapia = solicitacaoradioterapia;
		this.templatebiometrico = templatebiometrico;
		this.tipoetapaautorizacao = tipoetapaautorizacao;
		this.tipoident = tipoident;
		this.tipointernacao = tipointernacao;
		this.uf = uf;
		this.eventos = eventos;
		this.registroans = registroans;
	}
}