package com.benner.regulacao;
/**
 * This class was automatically generated by the data modeler tool.
 */
@javax.persistence.Entity
@org.kie.api.definition.type.Label("Guiaeventos")
public class guiaeventos implements java.io.Serializable {
	static final long serialVersionUID = 1L;
	// @javax.persistence.GeneratedValue(strategy =
	// javax.persistence.GenerationType.AUTO, generator =
	// "GUIAEVENTOS_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "GUIAEVENTOS_ID_SEQ", name = "GUIAEVENTOS_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Código do evento")
	private java.lang.String codigoprocedimento;
	@org.kie.api.definition.type.Label("Código da tabela")
	private java.lang.String codigotabela;
	@org.kie.api.definition.type.Label("Descrição do evento")
	private java.lang.String descricaoprocedimento;
	@org.kie.api.definition.type.Label("idguia")
	private java.lang.Long idguia;
	@org.kie.api.definition.type.Label("quantidadesolicitada")
	private java.lang.Long quantidadesolicitada;
	@org.kie.api.definition.type.Label("regulquantidadeautorizada")
	private java.lang.Long regulquantidadeautorizada;
	@org.kie.api.definition.type.Label("Situação")
	private java.lang.String regulsituacao;

	public guiaeventos() {
	}
	public java.lang.String getCodigoprocedimento() {
		return this.codigoprocedimento;
	}
	public void setCodigoprocedimento(java.lang.String codigoprocedimento) {
		this.codigoprocedimento = codigoprocedimento;
	}
	public java.lang.String getCodigotabela() {
		return this.codigotabela;
	}
	public void setCodigotabela(java.lang.String codigotabela) {
		this.codigotabela = codigotabela;
	}
	public java.lang.String getDescricaoprocedimento() {
		return this.descricaoprocedimento;
	}
	public void setDescricaoprocedimento(java.lang.String descricaoprocedimento) {
		this.descricaoprocedimento = descricaoprocedimento;
	}
	public java.lang.Long getId() {
		return this.id;
	}
	public void setId(java.lang.Long id) {
		this.id = id;
	}
	public java.lang.Long getIdguia() {
		return this.idguia;
	}
	public void setIdguia(java.lang.Long idguia) {
		this.idguia = idguia;
	}
	public java.lang.Long getQuantidadesolicitada() {
		return this.quantidadesolicitada;
	}
	public void setQuantidadesolicitada(java.lang.Long quantidadesolicitada) {
		this.quantidadesolicitada = quantidadesolicitada;
	}
	public java.lang.Long getRegulquantidadeautorizada() {
		return this.regulquantidadeautorizada;
	}
	public void setRegulquantidadeautorizada(
			java.lang.Long regulquantidadeautorizada) {
		this.regulquantidadeautorizada = regulquantidadeautorizada;
	}
	public java.lang.String getRegulsituacao() {
		return this.regulsituacao;
	}
	public void setRegulsituacao(java.lang.String regulsituacao) {
		this.regulsituacao = regulsituacao;
	}
	public guiaeventos(java.lang.String codigoprocedimento,
			java.lang.String codigotabela,
			java.lang.String descricaoprocedimento, java.lang.Long id,
			java.lang.Long idguia, java.lang.Long quantidadesolicitada,
			java.lang.Long regulquantidadeautorizada,
			java.lang.String regulsituacao) {
		this.codigoprocedimento = codigoprocedimento;
		this.codigotabela = codigotabela;
		this.descricaoprocedimento = descricaoprocedimento;
		this.id = id;
		this.idguia = idguia;
		this.quantidadesolicitada = quantidadesolicitada;
		this.regulquantidadeautorizada = regulquantidadeautorizada;
		this.regulsituacao = regulsituacao;
	}
	public guiaeventos(java.lang.Long id, java.lang.String codigoprocedimento,
			java.lang.String codigotabela,
			java.lang.String descricaoprocedimento, java.lang.Long idguia,
			java.lang.Long quantidadesolicitada,
			java.lang.Long regulquantidadeautorizada,
			java.lang.String regulsituacao) {
		this.id = id;
		this.codigoprocedimento = codigoprocedimento;
		this.codigotabela = codigotabela;
		this.descricaoprocedimento = descricaoprocedimento;
		this.idguia = idguia;
		this.quantidadesolicitada = quantidadesolicitada;
		this.regulquantidadeautorizada = regulquantidadeautorizada;
		this.regulsituacao = regulsituacao;
	}
}